### ISSUE TITLE
Unable to find a matching configuration of project

### ISSUE THREAD

**Issue by felocru** [johannesnormannjensen/capacitor-fused-location#2]
Hello, I have this problem:
Unable to find a matching configuration of project :johannesnormannjensen-capacitor-fused-location: None of the consumable configurations have attributes.

Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

Thanks for the plugin

**Comment by johannesnormannjensen** [comment]
Hi @felocru 

This project is now discontinued. Please use [jonoj-team/capacitor-fused-location](https://github.com/jonoj-team/capacitor-fused-location/tree/master) instead.

**Comment by felocru** [comment]
Thanks @johannesnormannjensen
